### ISSUE TITLE
NFC on Redmi 8T

### ISSUE THREAD

**Issue by SenyReturns** [PotatoDevices/device_xiaomi_ginkgo#1]
I'm trying to access the NFC settings that exist on the redmi 8T, but I can't activate/configure it and contactless payments are not working properly.
![Screenshot_20220212-143724_Configurações](https://user-images.githubusercontent.com/99555054/153723184-d75727a3-e9c1-4edd-9635-7dd87d52be27.png)
![Screenshot_20220212-151827_Settings](https://user-images.githubusercontent.com/99555054/153723341-6ae4a59f-5e71-4b26-8b93-3013fb8f9ffa.png)

**Comment by notakbuzz** [comment]
oh! will be sorted out in next version release thanks for info :) will inform u here closing as of now
